# [[main]]
#   identifier = "docs"
#   name = "Docs"
#   url = "docs"
#   weight = 1
[[main]]
  identifier = "home"
  name = "Home"
  url = "home"
  weight = 1

[[main]]
  identifier = "docs"
  name = "Docs"
  url = "docs"
  weight = 2
  collapsible = true

# [[main]]
#   identifier = "blog"
#   name = "Blog"
#   url = "blog"
#   weight = 3

# [[main]]
#   identifier = "devops"
#   name = "DevOps"
#   url = "devops"
#   weight = 4

# [[main]]
#   identifier = "meta"
#   name = "Meta"
#   url = "meta"
#   weight = 90

[[main]]
  identifier = "tags"
  name = "Tags"
  url = "blog"
  weight = 100
