name: release-drafter

on:
  push:
    branches:
      - $default-branch
      - master
      - main

  workflow_dispatch:
    inputs:
      prerelease:
        description: Is this a pre-release
        required: true
        default: true
      publish:
        description: Publish release
        required: false
        default: false

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:

      - name: check next version
        uses: anothrNick/github-tag-action@1.35.0
        id: tag
        env:
          DRY_RUN: true
          WITH_V: true
          DEFAULT_BUMP: patch

      - uses: release-drafter/release-drafter@v5.15.0
        with:
          publish: $ {{ contains(github.event.head_commit.message, 'publish') || github.event.inputs.publish }}
          prerelease: $ {{ contains(github.event.head_commit.message, 'release') || github.event.inputs.prerelease }}
          tag: ${{ steps.tag.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: versions
        run: |
          echo "release it: ${{ github.event.inputs.prerelease }}"
          echo "out: ${{ steps.release.name }}"
          echo "tag: ${{ steps.release.outputs.tag_name }}"
