name: owasp-zaproxy-full

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch, gh-pages ]
  schedule:
    - cron: '0 10 * * 0'

jobs:
  zap_full_scan:
    runs-on: ubuntu-latest
    name: Scan fully the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: ${{ secrets.ENDPOINT }}
          # rules_file_name: '.zap/rules.tsv'
          # cmd_options: '-a'
